### ISSUE TITLE
The code about levelset

### ISSUE THREAD

**Issue by sutiankang** [LiWentomng/boxlevelset#11]
Thank you for your great work.
I want to know about the specific implementation of level sets, but I don't know where the code is about level sets. Can you point me to the exact location of the level set code?
Thanks!

**Comment by LiWentomng** [comment]
@sutiankang 
Hi, the  level set function  code is in [levelset_loss.py](https://github.com/LiWentomng/boxlevelset/blob/main/mmdet/models/losses/levelset_loss.py) , the main codes of the model are in [head.py](https://github.com/LiWentomng/boxlevelset/blob/main/mmdet/models/dense_heads/box_solov2_head.py).
