### ISSUE TITLE
No length regularization in LevelsetLoss?

### ISSUE THREAD

**Issue by Yangr116** [LiWentomng/boxlevelset#15]
Hi, why is there not the third term (length regularization) in LevelsetLoss as described in Eq.3 of the paper? How many gains/drops will it bring?

**Comment by LiWentomng** [comment]
@Yangr116 
Hi, in the ablation study, the length regularization of Level set loss is adopted, which is beneficial for the performance (especially when the performance is low). In the main results, I found that the length regularization can bring the 0.2~0.4mAP drop. So, I commented the calculation for the better final results.

**Comment by Yangr116** [comment]
Thanks for your reply!
