### ISSUE TITLE
error: command '/usr/bin/g++' failed with exit code 1

### ISSUE THREAD

**Issue by liusurufeng** [LiWentomng/boxlevelset#17]
running build
running build_ext
building 'tree_filter_cuda' extension
Emitting ninja build file /home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2
g++ -pthread -B /home/1/anaconda3/envs/hongmoumou/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /home/1/anaconda3/envs/hongmoumou/compiler_compat -L/home/1/anaconda3/envs/hongmoumou/lib -Wl,-rpath=/home/1/anaconda3/envs/hongmoumou/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/build/temp.linux-x86_64-3.7/home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/src/bfs/bfs.o /home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/build/temp.linux-x86_64-3.7/home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/src/mst/boruvka.o /home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/build/temp.linux-x86_64-3.7/home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/src/mst/mst.o /home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/build/temp.linux-x86_64-3.7/home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/src/refine/refine.o /home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/build/temp.linux-x86_64-3.7/home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/src/tree_filter.o -L/home/anaconda3/envs/lib -L/home/1/anaconda3/envs/hongmoumou/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/tree_filter_cuda.cpython-37m-x86_64-linux-gnu.so
g++: error: /home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/build/temp.linux-x86_64-3.7/home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/src/bfs/bfs.o: 没有那个文件或目录
g++: error: /home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/build/temp.linux-x86_64-3.7/home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/src/mst/boruvka.o: 没有那个文件或目录
g++: error: /home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/build/temp.linux-x86_64-3.7/home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/src/mst/mst.o: 没有那个文件或目录
g++: error: /home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/build/temp.linux-x86_64-3.7/home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/src/refine/refine.o: 没有那个文件或目录
g++: error: /home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/build/temp.linux-x86_64-3.7/home/1/mmdetection-2.11.0/mmdetection-2.11.0/mmdet/ops/tree_filter/src/tree_filter.o: 没有那个文件或目录
error: command '/usr/bin/g++' failed with exit code 1

@LiWentomng 
when I used the script `(python setup.py build develop)` to comply the **tree_filter**,the problem was occuring，I have tried to comply the `bfs` to `bfs.o` ,but there was lack of the file of `bfs.cpp` ,how can I  solve the problem?

**Comment by Wenlve-Zhou** [comment]
I have same questions. Have u fixed?
