### ISSUE TITLE
关于水平集演化问题

### ISSUE THREAD

**Issue by Wenlve-Zhou** [LiWentomng/boxlevelset#18]
您好！你们做了非常有趣的工作，使我们受到很大的启发，十分感谢！关于水平集问题，想请问你们是否直接将水平集的初始化以及演化过程，均纳入至损失函数计算？也就是说没有显式演化水平集是吗？感谢回答~

**Comment by LiWentomng** [comment]
@Wenlve-Zhou 你好，是的，没有显式地演化水平集， 基于region-based  Chan-Vese 水平集来实现能量函数，该能量函数作为网络的损失函数，从而优化网络参数。

**Comment by Wenlve-Zhou** [comment]
十分感谢回答，祝一切顺利！
