### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by liuguol** [LiWentomng/boxlevelset#2]
Hello, how long does it take to use 2080ti for training? I have two 2080tis, so I want to know the length of training. Or what graphics card do you use and how long does it take to train？think you

**Comment by LiWentomng** [comment]
It needs about **1 day 12 hours**  (total 36 hours) for  training with **four 2080tis**.    This code is  based on an old version mmdetection,  so the training phase is 2x~3x slower than new mmedetection version.   I  plan to update  this code with the current mmdetection version.
