### ISSUE TITLE
VOC evaluation metric

### ISSUE THREAD

**Issue by voidrank** [LiWentomng/boxlevelset#3]
Hi @LiWentomng ,

Can you kindly inform me of the code being used for voc? Did you implement the python version?

Thanks!

**Comment by LiWentomng** [comment]
@voidrank  Hi.  I use the python implementation for voc evaluation.  I upload the evaluation [code](https://github.com/LiWentomng/boxlevelset/blob/main/tools/pascal_voc_evaluation/evaluate_voc.py) just now. This code can obtain ap25, ap50, ap70, ap75 and abo.

**Comment by voidrank** [comment]
Thanks @LiWentomng
