### ISSUE TITLE
iSAID

### ISSUE THREAD

**Issue by ZhangRan24** [LiWentomng/boxlevelset#4]
请问关于iSAID数据集，是基于旋转框注释还是基于水平框的呀。如果是基于mmrotate,能提供iSAID的模型代码就太感谢了。

**Comment by LiWentomng** [comment]
@ZhangRan24  Hi,  目前iSAID还是在水平框的监督下实现，也是基于此代码(mmdetection)，我会尽快给出pretrain models和对应的config文件。

**Comment by ZhangRan24** [comment]
感谢您的解答和回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiWentomng/boxlevelset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月24日(星期天) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiWentomng/boxlevelset] iSAID (Issue #4)





 
@ZhangRan24  Hi,  目前iSAID还是在水平框的监督下实现，也是基于此代码(mmdetection)，我会尽快给出pretrain models和对应的config文件。

**Comment by LiWentomng** [comment]
@ZhangRan24  Hi,  iSAID对应的pretrain models和对应的config文件， 已给出，欢迎尝试训练和使用我们的方法。

**Comment by ZhangRan24** [comment]
收到，非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiWentomng/boxlevelset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月26日(星期二) 晚上10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiWentomng/boxlevelset] iSAID (Issue #4)





 
@ZhangRan24  Hi,  iSAID对应的pretrain models和对应的config文件， 已给出，欢迎尝试训练和使用我们的方法。
