### ISSUE TITLE
Pretrained Weights for iSAID dataset

### ISSUE THREAD

**Issue by abhigoku10** [LiWentomng/boxlevelset#5]
@LiWentomng  hi thanks for sharing the work can y ou please share the pretrained weights for iSAID dataset on google drive or one drive 
THanks in advance

**Comment by LiWentomng** [comment]
@abhigoku10   Hi, I will share the `config`, `pretrained models` and more `visual results` for iSAID in a few day.

**Comment by abhigoku10** [comment]
@LiWentomng  thanks a lot for the response sure will wait for the release !!!

**Comment by LiWentomng** [comment]
@abhigoku10  Hi, I  have shared the `config`, `pretrained models` and `visual results` for iSAID.
