### ISSUE TITLE
Question regarding the LevelSetLoss implementation

### ISSUE THREAD

**Issue by QianyiWu** [LiWentomng/boxlevelset#6]
Thanks for your awesome work. 

I found in the implementation of LevelSetLoss that the term of length regularization is not calculated. Would you like to share the reason for it?

Besides that, what is the motivation that only calculates the loss for the positive samples in Eqn.(11) in the paper? 

Best

**Comment by LiWentomng** [comment]
@QianyiWu  Thanks. 

In the ablation study, the length regularization of Level set loss is adopted, which is beneficial for the performance (especially when the performance is low).  In the main results, I found that the length regularization can bring the 0.2~0.4mAP drop.  So,  I commented the calculation for the better final results.

About  only calculting the the loss for the positive samples,  this follows the original SOLOv2 network.  The positive samples comes from the label(target) assignment considering the GT box location and mask prediction.  Without this scheme, the network convergence is very slow, and  it can't even work.
